### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by quasiperfect** [Ulyanov-programmer/gulp-sharp-optimize-images#1]
hi

i wanted to try your lib but i get 
```
 Requiring external module @babel/register
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\laragon\www\florarie\node_modules\gulp-sharp-optimize-images\index.js from D:\laragon\www\florarie\task-runners\images.js not supported.
Instead change the require of index.js in D:\laragon\www\florarie\task-runners\images.js to a dynamic import() which is available in all CommonJS modules.
    at Object.newLoader [as .js] (D:\laragon\www\florarie\node_modules\pirates\lib\index.js:141:7)
    at Object.<anonymous> (D:\laragon\www\florarie\task-runners\images.js:11:27)
    at Module._compile (D:\laragon\www\florarie\node_modules\pirates\lib\index.js:136:24)
    at Object.newLoader [as .js] (D:\laragon\www\florarie\node_modules\pirates\lib\index.js:141:7)
    at requireDir (D:\laragon\www\florarie\node_modules\require-dir\index.js:128:33)
    at Object.<anonymous> (D:\laragon\www\florarie\gulpfile.babel.js:40:1)
    at Module._compile (D:\laragon\www\florarie\node_modules\pirates\lib\index.js:136:24)
    at Object.newLoader [as .js] (D:\laragon\www\florarie\node_modules\pirates\lib\index.js:141:7)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
```
any idea what i can do to solve this ?

**Comment by Ulyanov-programmer** [comment]
Hello!

Apparently, you are using images.js without support for ESM modules, as indicated by the fact that you use `require()`.

You have two options:

1: Change images.js so that it supports modules (so that the `import` syntax works in it).

2: You can try using dynamic import to take advantage of the library. 
`await import('gulp-sharp-optimize-images')`
But I'm not sure it will work.

**Comment by Ulyanov-programmer** [comment]
Closed after the expiration of the response period.

**Comment by quasiperfect** [comment]
thank you for your response :)
