### ISSUE TITLE
Not compatible with gulp v5?

### ISSUE THREAD

**Issue by barsch** [Ulyanov-programmer/gulp-sharp-optimize-images#3]
After upgrading to ```gulp.js@5.0.0``` I get the following traceback while using ```gulp-sharp-optimize-images```:

```
[11:12:29] Error: Input buffer contains unsupported image format
    at Sharp.toBuffer (D:\Workspace\egu\node_modules\sharp\lib\output.js:161:17)
    at convert (file:///D:/Workspace/egu/node_modules/gulp-sharp-optimize-images/index.js:86:38)
    at Transform._transform (file:///D:/Workspace/egu/node_modules/gulp-sharp-optimize-images/index.js:68:25)
    at Transform._read (D:\Workspace\egu\node_modules\gulp-sharp-optimize-images\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at Transform._write (D:\Workspace\egu\node_modules\gulp-sharp-optimize-images\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (D:\Workspace\egu\node_modules\gulp-sharp-optimize-images\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (D:\Workspace\egu\node_modules\gulp-sharp-optimize-images\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at Transform.Writable.write (D:\Workspace\egu\node_modules\gulp-sharp-optimize-images\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at Transform.ondata (node:internal/streams/readable:1007:22)
    at Transform.emit (node:events:518:28)
    at Transform.emit (node:domain:551:15)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Transform.Readable.push (node:internal/streams/readable:391:5)
    at node:internal/streams/transform:178:12
    at file:///D:/Workspace/egu/node_modules/easy-transform-stream/index.js:18:7
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

After downgrading to ```gulp.js@4.0.2``` it works again.

**Comment by Ulyanov-programmer** [comment]
Thanks for your feedback!
I haven’t tested it on gulp v.5, the release of gulp v.5 was a surprise for me, but I will work on the update in the near future.

**Comment by Ulyanov-programmer** [comment]
I made the changes in commit 4cd5c61ede91be2a7dc2c66d7a0a43f5f57dc838. Now, the plugin should work on both versions 4.0.2 and 5.0.0. Please test the plugin on your machine.

Write this in your `package.json`:
`"gulp-sharp-optimize-images": "github:Ulyanov-programmer/gulp-sharp-optimize-images#master",`

And try it.

**Comment by barsch** [comment]
works for me - thanks for the fast fix!
